services:
  dev:
    build: .
    container_name: verilator
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src:${HOME}/src
      - ./nvim:${HOME}/.config/nvim
      - ${HOME}/.local/share/nvim:${HOME}/.local/share/nvim # Optional: plugins
    working_dir: ${HOME}/src
    network_mode: "host"
    stdin_open: true
    tty: true
    command: bash

