services:
  verilator:
    build:
      context: .
    image: verilator
    container_name: verilator
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - USER_ID=${UID}
      - GROUP_ID=${GID}
      - USER_NAME=dev
    user: "0:0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:${XAUTHORITY}
      - ./:/workspace/src
    working_dir: /workspace/src
    stdin_open: true
    tty: true
    network_mode: host
